#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding		26
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Fix cursor.
xsetroot -cursor_name left_ptr

# Start X wallpaper.
feh --bg-scale "$HOME/wallpaper.jpg"

# Run polybar.
bash "${HOME}/.config/polybar/launch.sh"
